version: '2'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:latest'
    environment:
      - MARIADB_USER=bn_laravel
      - MARIADB_DATABASE=bitnami_laravel
      - MARIADB_PASSWORD=bitnami
      - MARIADB_ROOT_PASSWORD=root
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  laravel:
    image: 'docker.io/bitnami/laravel:latest'
    user: root
    entrypoint: ['/bin/sh', '-c']
    command: ['php artisan serve --host=0.0.0.0 --port=8000']
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=bn_laravel
      - DB_DATABASE=bitnami_laravel
      - DB_PASSWORD=bitnami
    volumes:
      - '.:/app'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
